In [1]:
import numpy as np

In [5]:
# Q7. Convert a 1D array to a 2D array with 2 rows
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# Q8. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
v = np.vstack((a,b))
v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
# Q9. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
h = np.hstack((a,b))
h


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [14]:
# Q10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]
# for numpy.repeat , check this website for knowing more
# https://numpy.org/doc/stable/reference/generated/numpy.repeat.html

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
# Q11. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

In [20]:
# Q12. From array a remove all items present in array 
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

In [7]:
# Q13. Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b) 
c

(array([1, 3, 5, 7], dtype=int64),)

In [34]:
# Q14. Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = np.where((a>5)&(a<10))
a[b]

array([6, 9])

In [43]:
# Q15. Convert the function maxx that works on two scalars, to work on two arrays.
def findmax(x, y):
    if x>=y:
        return x
    else:
        return y

max = np.vectorize(findmax, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
max(a,b)


array([6., 7., 9., 8., 9., 7., 5.])

In [54]:
#Q16. Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]] 



array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [69]:
# Q17. Swap rows 1 and 2 in the array 
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [76]:
# Q18. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [78]:
# Q19. Reverse the columns of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [90]:
# Q20. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
a = np.random.randint(low=5,high=10, size=(5,3)) + np.random.random((5,3))
a

array([[7.53401083, 9.15609218, 7.27341096],
       [6.43020876, 8.08976823, 8.50845021],
       [6.8169633 , 9.81282941, 5.3505851 ],
       [7.64325721, 8.57848508, 9.40510166],
       [9.25675533, 7.74905936, 9.34077597]])