In [1]:
import numpy as np

In [6]:
# 1D Array
a = np.array([5,6,9])
a

array([5, 6, 9])

In [7]:
# 2D Array
a = np.array([[5,2],[6,9],[8,9]])
a

array([[5, 2],
       [6, 9],
       [8, 9]])

In [8]:
# Check Dimensions of last array
a.ndim

2

In [9]:
# size of element
a.itemsize

4

In [10]:
#check datatype of element
a.dtype

dtype('int32')

In [13]:
#change datatype of element
a = np.array([[5,2],[6,9],[8,9]], dtype=np.float64)
a

array([[5., 2.],
       [6., 9.],
       [8., 9.]])

In [14]:
#total number in array
a.size

6

In [15]:
#shape(RowsxColumn) of array
a.shape

(3, 2)

In [16]:
# Zeros Array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# ones Array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# Range in numpy
l = range(5)
l

range(0, 5)

In [25]:
#arange() function , you can arange a numbersin array
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# diffrence of any number in arange()   #(start,end,diff)
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [27]:
# linspace() , you can find many numbers between any 2 number   #(num1, num2, how many num do you want to find bw them)
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [55]:
a = np.array([[5,2],[6,9],[8,25]], dtype=np.int64)
a.shape

(3, 2)

In [56]:
# Reshape an array in any dimension
a.reshape(2,3)

array([[ 5,  2,  6],
       [ 9,  8, 25]], dtype=int64)

In [57]:
#ravel(), convert any array in to 1D Array
a.ravel()

array([ 5,  2,  6,  9,  8, 25], dtype=int64)

In [58]:
# find min element in the array
a.min()

2

In [59]:
# find max element in the array
a.max()

25

In [60]:
#sum of all the elemnt of array
a.sum()

55

In [61]:
a

array([[ 5,  2],
       [ 6,  9],
       [ 8, 25]], dtype=int64)

In [62]:
# sum of rows => axis=0
a.sum(axis=0)

array([19, 36], dtype=int64)

In [63]:
# sum of column => axis=1
a.sum(axis=1)

array([ 7, 15, 33], dtype=int64)

In [64]:
a

array([[ 5,  2],
       [ 6,  9],
       [ 8, 25]], dtype=int64)

In [65]:
# Square Root
np.sqrt(a)

array([[2.23606798, 1.41421356],
       [2.44948974, 3.        ],
       [2.82842712, 5.        ]])

In [66]:
# Standard Deviation
np.std(a)

7.425556469981821

In [67]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [68]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [72]:
# Operaions in Array
a+b, a-b, a*b, a/b


(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [73]:
#matrix dot product()
a.dot(b)

array([[19, 22],
       [43, 50]])