In [1]:
# Topics covered in this file will be:
#1 Indexing and slicing
#2 Iterating through arrays
#3 Stacking together two arrays
#4 Indexing with boolean arrays
#5 Iterate numpy array using nditer  # numpy nditer

In [5]:
#1 Indexing and slicing
# Indexing: Array Indexing The array indexing means accessing a row’s particular item, row, column,
# or plane in the case of multidimensional arrays. 
# Indices are primarily integers that tell the position of an element in the given array. Furthermore, 
# it is essential to note that the arrays usually start from the zeroth index and so forth.


# Slicing: Slicing in python means taking elements from one given index to another given index.

In [6]:
import numpy as np 

In [7]:
#1.1 1D array
n =[6,7,8] 
n[0:2] #it will print element 0 to last-1

[6, 7]

In [8]:
#1.2 for printing last element
n[-1]

8

In [9]:
#1.3 Multi-dimensional array
a = np.array([[6,7,8],[1,2,3],[2,5,6,]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [2, 5, 6]])

In [10]:
#1.4 get value of element by using position of element
a[1,2]  #a[row,column]

3

In [11]:
#1.5 a[0:2, which element do you want]
a[0:2, 2]

array([8, 3])

In [12]:
#1.6 for printing last rows element
a[-1]

array([2, 5, 6])

In [13]:
#1.7 print last row's element from range(start:end-1)
a[-1, 0:2]

array([2, 5])

In [15]:
#1.8 not print first row
a[:,1:3]

array([[7, 8],
       [2, 3],
       [5, 6]])

In [16]:
#2 Iterating through arrays

In [17]:
a = np.array([[6,7,8],[1,2,3],[2,5,6,]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [2, 5, 6]])

In [18]:
#2.1 print array as row
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[2 5 6]


In [20]:
#2.2 multi-dimensional array into single array  # use .flat
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
2
5
6


In [7]:
#3 Stacking together two arrays
import numpy as np 
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [13]:
#3.1 put array in vertical and horizontal direction  #vstack, hstack
np.vstack((a,b,)), np.hstack((a,b))

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  1,  6,  7],
        [ 2,  3,  8,  9],
        [ 4,  5, 10, 11]]))

In [28]:
# Split array in vertical and horizontal direction 
a = np.arange(30).reshape(2,15)
result = np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [29]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [30]:
result = np.vsplit(a,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [31]:
#4 Indexing with boolean arrays

In [32]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
#4.1 True -> where condition is right
# False -> where condition gone wrong
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
#4.2 return only "true" values
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [36]:
#4.3 Replace value 
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [56]:
#5 numpy nditer:
#It is an efficient multidimensional iterator object using which it is possible to iterate over an array.
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [58]:
#5.1 use order='C' for flatten in nditer
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [59]:
#5.2 printing flatten(Row by Row) use order='F', Fortran Order
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [60]:
#5.3 print everyrow as column using external_loop 'flag'
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [61]:
#5.4 op_flags
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [62]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [63]:
#5.5 General Broadcasting Rules
# When operating on two arrays, NumPy compares their shapes element-wise. 
# It starts with the trailing (i.e. rightmost) dimensions and works its way left.
#Two dimensions are compatible when
#1 they are equal, or
#2 one of them is 1

for x, y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
